### ISSUE TITLE
Verify QC hospitalization data

### ISSUE THREAD

**Issue by jeanpaulrsoucy** [ccodwg/CovidTimelineCanada#104]
Check for COVID/with COVID, as referenced in the figure here:

https://twitter.com/Aaron_Derfel/status/1628562019614949377

See how far back data making this distinction goes. For example, AB data making this distinction only goes back to early 2022 (#82).

**Comment by jeanpaulrsoucy** [comment]
The datasets:

- `f0c25e20-2a6c-4f9a-adc3-61b28ab97245` (MSSS, currently used)
- `3b93b663-4b3f-43b4-a23d-cbf6d149d2c5` (INSPQ)

have the same data and same start date (2020-04-10), but the former is updated more frequently.

The dataset: `b78d46c8-9a56-4b75-94c5-4ace36e014f5` (INSPQ) is no longer updated but has data beginning earlier (2020-03-15) using an old definition.

These two datasets are combined to show the time series in figure 3.1 of the [INSPQ website](https://www.inspq.qc.ca/covid-19/donnees).

The dataset `3b93b663-4b3f-43b4-a23d-cbf6d149d2c5` (INSPQ) also has additional time series related to hospitalizations/ICU "with" and "for" COVID. These power figure 3.2 of the [INSPQ website](https://www.inspq.qc.ca/covid-19/donnees). This figure covers admissions rather than occupancy.

However, the [tweet](https://twitter.com/Aaron_Derfel/status/1628562019614949377) referenced above covers occupancy, not admissions.

![image](https://github.com/ccodwg/CovidTimelineCanada/assets/31170087/73a7abce-1e06-4b18-acea-05e941b3c0dd)

The caption references MSSS. Are the for/with occupancy data part of one of the aforementioned datasets or was this figure derived from a privately requested dataset?

**Comment by kbelisar** [comment]
The datasets listed above do not contain any data regarding occupancy. I wonder if it could be mis-wording where they should have referenced admissions?

The MSSS do not list any variables regarding for/with distinction in their data dictionary [here](https://www.donneesquebec.ca/recherche/dataset/99517f1f-9e4d-4853-98da-47f7cafb4d77/resource/2227d1b2-8449-4a3d-9c3b-682226dfe687/download/listevariables_notesmetho_hospit_20230412.pdf). Occupancy could be calculated from subtracting cumulative discharged from cumulative admissions, however I don't see any numbers regarding discharges. Additionally, there are numerous proportions, but none seem to correspond with occupancy. I've checked the dates and for/with numbers in the captured tweet, and do not see any matches with the available dataset.

**Comment by jeanpaulrsoucy** [comment]
The occupancy data reported in the tweet above appears to be a one-off: probably released as part of a media request on behalf of La Presse. While *admissions* data are broken down by with/for in the INSPQ dataset, this does not seem to be the case for occupancy data.
