### ISSUE TITLE
MB hospitalization/ICU data not updated

### ISSUE THREAD

**Issue by xyrophile** [ccodwg/CovidTimelineCanada#110]
Manitoba's hospitalization and ICU occupancy figures are currently listed as 291 and 5 respectively for all dates since 2022-07-27.

**Comment by jeanpaulrsoucy** [comment]
Thanks @xyrophile. Hospital and ICU occupancy figures stopped being reported by the province on 2022-03-25, as far as I can tell (see #82). I've removed the out-of-date data, which was retrieved from covid19tracker.ca after this date. I will endeavor to add current and historical data on the number of hospital and ICI *admissions* which continue to be reported on a weekly basis (see #111).

**Comment by jeanpaulrsoucy** [comment]
I've added new experimental hospital/ICU admissions datasets (#111):

- https://github.com/ccodwg/CovidTimelineCanada/blob/main/data/pt/hosp_admissions_pt.csv
- https://github.com/ccodwg/CovidTimelineCanada/blob/main/data/pt/icu_admissions_pt.csv

So far, I've only added data from Manitoba, but it stretched all the way from May 2020 to the present day.
