### ISSUE TITLE
Create automatically updated github.io page

### ISSUE THREAD

**Issue by jeanpaulrsoucy** [ccodwg/CovidTimelineCanada#12]
This could be useful for displaying plots of data, update notes, etc.

**Comment by timothoms** [comment]
Automatically updating a website through a GitHub repository is quite useful, but, unless it's just one or two data series, perhaps not the best way for displaying plots. I had done this for earlier versions of my site on just one QC region (https://timothoms.github.io/covid19Outaouais/): a daily script automatically scraped or downloaded key data sources, assembled them into tidy datasets, and the made a series of web pages with figures and by automatically pushing the changes to GitHub, updated the github.io site. (An example of this old way is at https://timothoms.github.io/covid19Outaouais/situation.html.) It worked quite well, but I have changed this to assembling all data into one dataset, which is called up on demand by a Shiny app, to simplify the site, make it interactive, and make the updating  process more efficient and robust.

**Comment by jeanpaulrsoucy** [comment]
@timothoms Fair enough, I'm mainly thinking a slightly nicer version of the summary plots (https://github.com/ccodwg/CovidTimelineCanada#included-datasets) that are already included & generated on data update.

**Comment by jeanpaulrsoucy** [comment]
An automatically updated JavaScript dashboard has been added: [` CovidTimelineCanada-js-dashboard`](https://github.com/ccodwg/CovidTimelineCanada-js-dashboard) at the following link: [https://ccodwg.github.io/CovidTimelineCanada-js-dashboard/](https://ccodwg.github.io/CovidTimelineCanada-js-dashboard/). At the moment, you can view all available values at either the Canadian or province/territory levels.

**Comment by jeanpaulrsoucy** [comment]
Further discussion can take place in the [`CovidTimelineCanada-js-dashboard`](https://github.com/ccodwg/CovidTimelineCanada-js-dashboard) repo.
