### ISSUE TITLE
name column not in cases_prov.csv

### ISSUE THREAD

**Issue by mister-elliott** [ccodwg/CovidTimelineCanada#15]
most if not all csv files have the name of the data type in column 0, but not cases_prov.csv or mortality_prov.csv.  Can you add that?  I can determine the type from the file name, but consistency is nice.  (also: "value_total" instead of "value", might be more consistent with naming of "value_daily" )

**Comment by mister-elliott** [comment]
will the dataset have vaccination data, and, if so, at what granularity?

**Comment by mister-elliott** [comment]
will you have update_time.txt in the new repo?  It is convenient to know the timestamp of the data update.  Date alone is good enough for each row of data.

**Comment by jeanpaulrsoucy** [comment]
> most if not all csv files have the name of the data type in column 0, but not cases_prov.csv or mortality_prov.csv. Can you add that? I can determine the type from the file name, but consistency is nice. (also: "value_total" instead of "value", might be more consistent with naming of "value_daily" )

That was an oversight! Will make sure it's in all future files.

If we add more data, "value_total" might be a little *too* specific. For example, some jurisdictions don't report active hospitalizations but do report the *total* number of people that have been hospitalized. So I'm not sure that "value_total" makes sense for the active hospitalization time series, for example.

> will the dataset have vaccination data, and, if so, at what granularity?

Coverage and distribution data will be added, either at launch or very shortly after.

> will you have update_time.txt in the new repo? It is convenient to know the timestamp of the data update. Date alone is good enough for each row of data.

Good point. Yes, this will be added.
