### ISSUE TITLE
Add population values to geo

### ISSUE THREAD

**Issue by jeanpaulrsoucy** [ccodwg/CovidTimelineCanada#23]

**Comment by apiology** [comment]
Hi @jeanpaulrsoucy!  The API change [disabled data updates](https://github.com/microCOVID/microCOVID/issues/1436) at [microCOVID.org](https://microcovid.org) and I'm trying to (unofficially) help out getting the new format ingested.  

It looks like microCOVID relied on population data in order to calculate prevalence by health region.

If you happen to be aware of another upstream source for population, that'd be helpful in the interim.

**Comment by jeanpaulrsoucy** [comment]
Hi @apiology, thanks for letting me know. What a cool project! At minimum, I can add population data for the provinces to [pt.csv](https://github.com/ccodwg/CovidTimelineCanada/blob/main/geo/pt.csv) later today.

As for dealing with the new data format, see the [note in the README](https://github.com/ccodwg/CovidTimelineCanada#timeline-of-covid-19-in-canada) giving links to case and death CSV files in the legacy format (i.e., the same format used for `Covid19Canada`).

**Comment by apiology** [comment]
@jeanpaulrsoucy: Appreciate it - we have province-level [population](https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv) and timeseries data for Canada already, so I think we're really looking for things at the health-region level.  Where were you gathering health-region population from previously?

I did see that note, thank you--the legacy format doesn't contain the health-region-level population, so I don't think it would help us with this.  I'll keep it in mind as I get further into this problem, though, perhaps there's another application.

**Comment by jeanpaulrsoucy** [comment]
Ah okay, in that case I can add the HR-level population data too. I didn't see the HR data being used in my quick scan of the site.

**Comment by apiology** [comment]
It's not currently - it had to be yanked because of this issue.  It'll be added back once we can get your data ingested again.

**Comment by apiology** [comment]
Ah, it looks like I can grab this from the legacy repo at https://github.com/ccodwg/Covid19Canada/blob/master/other/hr_map.csv in the interim (the existing code was using `https://api.opencovid.ca/other?stat=hr`).

**Comment by jeanpaulrsoucy** [comment]
Hi @apiology, see geo/pt.csv and geo/health_regions.csv for the latest population data. In particular, use the `pop` column for the latest population data available for the geography. Data notes are [here](https://github.com/ccodwg/CovidTimelineCanada/blob/main/geo/README.md).

Let me know if you have any questions or issues!

**Comment by apiology** [comment]
Thanks so much!  I've gotten a lot farther in other areas of the transition in the meantime.  I'll give it a shot and give you a shout if there are any problems!

**Comment by apiology** [comment]
@jeanpaulrsoucy: I am seeing a potential issue while doing QC on https://github.com/microCOVID/microCOVID/pull/1452

When microCOVID.org fetches a vaccination report for health region 595 (Vancouver Coastal, BC) from api.covid19tracker.ca [here](https://api.covid19tracker.ca/reports/regions/595?fill_dates=true&after=2022-05-11&before=2022-05-27), I see it claim that there are 1.1million people vaccinated (see `total_vaccinated` in the data).

However, your data claims a total population much less than that [here](https://raw.githubusercontent.com/ccodwg/CovidTimelineCanada/main/geo/health_regions.csv) - 300,970.

Which do you think is correct/incorrect?

**Comment by jeanpaulrsoucy** [comment]
Hi @apiology, thanks for catching this! The labels on some of the BC health regions got switched. This has been fixed in `health_regions.csv`, `health_regions.geojson` and all of the data files. #55

**Comment by apiology** [comment]
@jeanpaulrsoucy - thanks for the fast turnaround!  However, the population for hruid 595 (now labeled Northern Health), is still out of line with the `total_vaccinated` data I'm seeing from api.covid19tracker.ca [here](https://api.covid19tracker.ca/reports/regions/595?fill_dates=true&after=2022-05-11&before=2022-05-27), which is fetched via the hruid 595.

Thoughts?  I see the same issue for hruid 592.

**Comment by jeanpaulrsoucy** [comment]
Hmm, may be an error on their end then. (Link to [BC health regions IDs from StatCan](https://www12.statcan.gc.ca/census-recensement/2011/dp-pd/prof/help-aide/Q01.cfm?Lang=E))

Some screenshots from the [BC dashboard](https://experience.arcgis.com/experience/a6f23959a8b14bfa989e3cda29297ded):

Northern (595):

![595](https://user-images.githubusercontent.com/31170087/170848663-c3dcf9ae-4793-4233-8a07-6a96a5ee3814.png)

Total doses are 537,461, which makes sense with a total population ~300k.

Fraser (592):

![592](https://user-images.githubusercontent.com/31170087/170848716-bb99aa3c-fa24-45af-b60f-db66b534796e.png)

Total doses are 4,199,845, which makes sense with a total population ~2 million.

This is also ~consistent with what is reported on the [covid19tracker.ca page of BC vaccination](https://covid19tracker.ca/provincevac.html?p=BC). So it seems this is just a problem of HRUID labels in the API.

**Comment by jeanpaulrsoucy** [comment]
Okay, I figured it out.

The health region IDs for BC used by covid19tracker.ca are wrong: https://api.covid19tracker.ca/province/BC/regions
...but this traces back to the health region IDs for BC used by us in `Covid19Canada` being wrong: https://github.com/ccodwg/Covid19Canada/blob/master/other/hr_map.csv
...but this traces back to the health region IDs for BC used by ESRI (for their map file) being wrong: https://resources-covid19canada.hub.arcgis.com/datasets/covid19canada::health-region-summaries

However, our current HRUIDs for BC are now correct, according to both [StatCan](https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1710013401) and [BC itself](https://catalogue.data.gov.bc.ca/dataset/health-authority-boundaries).

**Comment by jeanpaulrsoucy** [comment]
I've sent a note to @noahlittle so hopefully we can get aligned on this shortly. :)
