### ISSUE TITLE
Add wastewater data

### ISSUE THREAD

**Issue by jeanpaulrsoucy** [ccodwg/CovidTimelineCanada#36]
Wastewater data are now available from PHAC for 6 jurisdictions: [Wastewater surveillance dashboard](https://health-infobase.canada.ca/covid-19/wastewater/)

**Comment by rahularoradfs** [comment]
Adding a +1 to this comment, although there are major questions about how to standardize this data - thinking about / reckoning with this at SeroTracker

**Comment by jeanpaulrsoucy** [comment]
For sure. Great work being done by Doug Manuel & team on the [Public Health Environmental Surveillance Open Data Model](https://github.com/Big-Life-Lab/PHES-ODM), which I suspect feeds into the data presented on the PHAC dashboard.

**Comment by jeanpaulrsoucy** [comment]
We may be able to add to the data available directly from PHAC by scraping the data found at the individual PHU/municipality/organization dashboards [linked at the bottom of the page](https://health-infobase.canada.ca/covid-19/wastewater/#links).

**Comment by jeanpaulrsoucy** [comment]
What should be the value name for wastewater? Should we specify units (e.g., `wastewater_copies_ml` or `wastewater_cp_ml`) or use something more general (`wastewater_viral_load`). Regardless of the name, we will have to use a standard unit. Viral copies per mL (cp/mL) seems to be the way to go, per the [[PHES-ODM](https://github.com/Big-Life-Lab/PHES-ODM)](https://github.com/Big-Life-Lab/PHES-ODM/blob/main/metadata_en.md).

I checked a handful of the other dashboards linked on the PHAC page, and these are the units they used:

- [Ontario Science Table](https://covid19-sciencetable.ca/ontario-dashboard/): standardized concentration of gene copies (about two orders of magnitude smaller than the PHAC numbers)
- [Alberta wastewater tracker](https://covid-tracker.chi-csm.ca/): copies/mL
- [USask](https://water.usask.ca/covid-19/): normalized virus load/100mL (i.e., copies/100mL) (reports normalized virus load as well as Omicron-specific)
- [NWT](https://nwt-covid.shinyapps.io/Testing-and-Cases/?lang=1): copies/mL
- [Quebec](https://centreau.org/en/covid/): Discontinued

So it seems reasonable to report a single value for `wastewater_copies_per_ml` or similar name. Perhaps additional details (e.g., normalized, average, N1 or N2) could eventually be reported using a grouping variable. Wastewater data using alternative units, on the other hand, probably merits a separate value.

There are also options to report more specific values like N1 or N2 copies, but perhaps this would go in the future "grouping variable" category.

**Comment by jeanpaulrsoucy** [comment]
The current adaptation of the PHAC wastewater dataset will continue to be maintained, but there is no capacity to add additional wastewater datasets at this time.
