### ISSUE TITLE
real format numbers in integer field

### ISSUE THREAD

**Issue by mister-elliott** [ccodwg/CovidTimelineCanada#42]
I assumed value_daily would always be a simple integer value, the actual number of whatever data is being counted for that day. 
but....

"vaccine_coverage_dose_1","AB","2021-01-30",2.03,0.00999999999999979
"vaccine_coverage_dose_1","AB","2021-01-31",2.03,0
"vaccine_coverage_dose_1","AB","2021-02-01",2.03,0
"vaccine_coverage_dose_1","AB","2021-02-02",2.03,0
"vaccine_coverage_dose_1","AB","2021-02-03",2.03,0
"vaccine_coverage_dose_1","AB","2021-02-04",2.03,0
"vaccine_coverage_dose_1","AB","2021-02-05",2.03,0
"vaccine_coverage_dose_1","AB","2021-02-06",2.04,0.0100000000000002

**Comment by jeanpaulrsoucy** [comment]
Most values are integers, but vaccine coverage, as a percentage, is a float.

**Comment by mister-elliott** [comment]
Thank you for rounding those numbers.  Are you going to report absolute numbers for vaccines doses in future or only percentages.

**Comment by jeanpaulrsoucy** [comment]
Yes @mister-elliott, this is planned (#47), especially since the dose administration dataset now contains information missing from the vaccine coverage dataset (5th doses for some PTs).
