### ISSUE TITLE
Consider adding age-structured case, vaccination, and death data

### ISSUE THREAD

**Issue by rahularoradfs** [ccodwg/CovidTimelineCanada#44]
Age is very helpful in understanding COVID severity and patterns of transmission. Moreover, vaccine distribution was also age-structured. If the data sources permit, it would be helpful to add age-structured time series of these datasets. 

An ideal case might be by 10-year age band, but the data for this is, understandably, limited

**Comment by jeanpaulrsoucy** [comment]
The most consistent age-structured case/death dataset covering all of Canada is the [PHAC/StatCan case-level dataset](https://www150.statcan.gc.ca/n1/pub/13-26-0003/132600032020001-eng.htm). Should be relatively simple to write a conversion script for it (in fact, I've probably done so half a dozen times for ad-hoc visualizations I've produced over the years). The only caveat is that it's not *quite* at the level of individual provinces and territories but rather *groups* of PTs.
