### ISSUE TITLE
Assemble report about reporting frequency

### ISSUE THREAD

**Issue by jeanpaulrsoucy** [ccodwg/CovidTimelineCanada#65]
With [Saskatchewan set to move to monthly reporting](https://www.saskatchewan.ca/government/news-and-media/2022/june/23/covid-19-weekly-epi-report), it would be good to set up a reporting frequency dataset which could be updated to automatically generate a report and perhaps be displayed on a dashboard.

> In recent weeks, COVID-19 surveillance indicators suggest a decreasing trend in COVID-19 infections. As we move into the summer months, the Ministry of Health will be transitioning to monthly COVID-19 situation reports. There will be a weekly report released on June 30, and then the transition will begin. On July 21, a 3-week report will be released (reporting period of June 26 to July 16). The first monthly report will be released on August 18 (with a reporting period of July 17 to August 13).  There will no longer be a news release announcing the release of the report. The epidemiological report will continue to be released at 1:30 p.m. on Thursdays monthly and will be posted on the Government of Saskatchewan website.

**Comment by jeanpaulrsoucy** [comment]
Note that the new Saskatchewan CRISP report currently has no value for `release_schedule`, as I haven't figured out how to incorporate biweekly reporting into the update math. Since the report is new, it also remains to be seen whether it will be truly biweekly or simply twice per month.

**Comment by kbelisar** [comment]
For Saskatchewan/ other provinces which moved to bi-weekly reporting, I'd change the `release_schedule` variable to only give days of the week the report falls on (which really is only important for those with multiple release dates, i.e. daily). By dropping the "weekly" or "daily" from this variable, we'd move it to a second variable - one that stores schedule frequency, so 7 for weekly, 14 for bi-weekly, etc. Then the number of days in the schedule frequency column can be added to the last date for which there is data, to calculate when the next report should be out. Happy to work on this!

**Comment by jeanpaulrsoucy** [comment]
Great idea, @kbelisar, can you open a pull request when you've updated `docs/data_sources/data_sources.csv` to split the `release_schedule` column into `release_schedule_dotw` and `release_schedule_freq` (i.e., day-of-the-week and frequency). Please also keep/update as necessary the `release_schedule_notes` column.

**Comment by jeanpaulrsoucy** [comment]
Most jurisdictions have moved to weekly or monthly reporting. The diffs dataset (#20) is capable of conveying the pace of updates, if integrated into `CovidTimelineCanada-js-dashboard`. The reporting frequency and associated variables in `data_sources.csv` are still useful for internal use.
